version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - esnet
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    networks:
      - esnet
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
    external: true

networks:
  esnet:
    driver: bridge
