version: '3'

services:
  zookeeper:
    image: zookeeper
    volumes:
      - zookeeper-data:/data
    ports:
      - "2181:2181"
    networks:
      - kafka-net
  kafka:
    image: ches/kafka
    volumes:
      - kafka-data:/data
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:
      ZOOKEEPER_IP: zookeeper
    depends_on:
      - zookeeper

volumes:
  zookeeper-data:
    external: true
  kafka-data:
    external: true

networks:
  kafka-net:
    driver: bridge
